ECommerceMVC/WebUI/Areas/Administrator/Controllers/CategoryController.cs
using Model.Entity;
using Service.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Areas.Administrator.Data;

namespace WebUI.Areas.Administrator.Controllers
{
    public class CategoryController : Controller
    {
        CategoryService categoryService = new CategoryService();
        SubCategoryService subCategoryService = new SubCategoryService();

        public ActionResult Index()
        {
         List<CategoryVM> categoryVMList = new List<CategoryVM>();
            foreach (var c in categoryService.GetList())
            {
              
                CategoryVM categoryVM = new CategoryVM();
                categoryVM.CategoryName = c.CategoryName;
                categoryVM.Description = c.Description;
                categoryVM.SubCategories = subCategoryService.GetDefault(x => x.CategoryId == c.ID);
                categoryVMList.Add(categoryVM);
            }
            ViewBag.CategoryVM = categoryVMList;
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Category newCategory)
        {
           string result= categoryService.Add(newCategory);
            TempData["Result"] = result;
            return RedirectToAction("Index");
        }

        //todo: Kategori Güncelleme

        //todo: Kategori Silme
    }
}

ECommerceMVC/WebUI/Areas/Administrator/Controllers/SubCategoryController.cs
using Model.Entity;
using Service.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Areas.Administrator.Controllers
{
    [Authorize(Roles = "admin")]
    public class SubCategoryController : Controller
    {

        SubCategoryService subCategoryService = new SubCategoryService();
        CategoryService categoryService = new CategoryService();

        public ActionResult Index()
        {
            return View(subCategoryService.GetList());
        }

        public ActionResult Add()
        {
            ViewBag.Categories = new SelectList(categoryService.GetList(), "ID", "CategoryName");
            return View();
        }

        [HttpPost]
        public ActionResult Add(SubCategory newSubCategory)
        {
           string result= subCategoryService.Add(newSubCategory);
            TempData["Result"] = result;

            return RedirectToAction("Index");
        }
    }
}

ECommerceMVC/WebUI/Areas/Administrator/Views/SubCategory/Add.cshtml
@model SubCategory
@{
    ViewBag.Title = "Alt Kategori Ekle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                @ViewBag.Title
            </header>
            <div class="panel-body">
                <form class="form-horizontal" role="form" method="post">
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Alt Kategori Adı</label>
                        <div class="col-lg-10">
                            <input name="SubCategoryName" type="text" class="form-control" placeholder="kategori adı">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Açıklama</label>
                        <div class="col-lg-10">
                            <input name="Description" type="text" class="form-control" placeholder="açıklama">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Kategori:</label>
                        <div class="col-lg-10">

                            @Html.DropDownListFor(x => x.CategoryId, (SelectList)ViewBag.Categories, new { @class = "form-control m-bot15" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button type="submit" class="btn btn-danger">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>

ECommerceMVC/WebUI/Areas/Administrator/Views/SubCategory/Index.cshtml
@model List<SubCategory>
@{
    ViewBag.Title = "Alt Kategori Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .label-info a {
        color: white;
        font-weight: bold;
    }
</style>

@if (TempData["Result"] != null)
{
    <div class="alert alert-success">
        <span>@TempData["Result"]</span>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="row">
                    <div class="col-lg-9">
                        @ViewBag.Title
                    </div>
                    <div class="col-lg-3">
                        @Html.ActionLink("Kategori Listesi", "Index", "Category", null, new { @class = "btn btn-sm btn-primary pull-right" })

                        @Html.ActionLink("Alt Kategori Ekle", "Add", "SubCategory", null, new { @class = "btn btn-sm btn-success pull-right" })
                    </div>
                </div>
            </header>
            <table class="table table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th>Kategori Adı</th>
                        <th>Açıklama</th>
                        <th>Ürün Sayısı</th>
                        <th><i class=" icon-edit"></i> Düzenleme</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (SubCategory c in Model)
                    {
                        <tr>
                            <td>@c.SubCategoryName</td>
                            <td>@c.Description</td>
                            <td>

                                @switch (c.Status)
                                {
                                    case Core.CoreEnum.Status.None:
                                        <span class="label label-default label-mini">
                                            Kayıt Dışı
                                        </span>
                                        break;
                                    case Core.CoreEnum.Status.Active:
                                        <span class="label label-success label-mini">
                                            Aktif
                                        </span>
                                        break;
                                    case Core.CoreEnum.Status.Deleted:
                                        <span class="label label-danger label-mini">
                                            Silinmiş
                                        </span>
                                        break;
                                    case Core.CoreEnum.Status.Updated:
                                        <span class="label label-warning label-mini">
                                            Güncellendi
                                        </span>
                                        break;
                                    default:
                                        break;
                                }





                            </td>
                            <td>
                                <button class="btn btn-success btn-xs"><i class="icon-ok"></i></button>
                                <button class="btn btn-primary btn-xs"><i class="icon-pencil"></i></button>
                                <button class="btn btn-danger btn-xs"><i class="icon-trash "></i></button>
                            </td>
                        </tr>
                    }





                </tbody>
            </table>
        </section>
    </div>
</div>